language: node_js
node_js:
  - "4.8.0"
script: npm run $COMMAND
env:
  - COMMAND=test
  #  - COMMAND=integration MOP_VERSION=. MR_VERSION=0.13
#  - COMMAND=integration MOP_VERSION=. MR_VERSION=0.14
  - COMMAND=integration MR_VERSION=0.15 MOP_VERSION=latest
  - COMMAND=integration MR_VERSION=0.16.0 MOP_VERSION=latest
  - COMMAND=integration MR_VERSION=latest MOP_VERSION=latest
  - COMMAND=integration MR_VERSION=#master MOP_VERSION="#master"
  - COMMAND=integration MONTAGE_VERSION=latest MOP_VERSION=0.13
  - COMMAND=integration MONTAGE_VERSION=latest MOP_VERSION=latest
  - COMMAND=integration MONTAGE_VERSION=#master MOP_VERSION="#master"
notifications:
  irc:
    channels:
      - "chat.freenode.net#montage"
    on_success: false
    template:
      - "%{author} broke the %{repository} tests on %{branch}: %{build_url}"