language: node_js
node_js:
  - "4.8.0"
script: npm run $COMMAND
env:
  - COMMAND=test
#  - COMMAND=integration MR_VERSION=0.15 MOP_VERSION=0.13 DEBUG=true
  - COMMAND=integration MR_VERSION=16.0.5 MOP_VERSION=latest DEBUG=true
  - COMMAND=integration MR_VERSION=latest MOP_VERSION=latest DEBUG=true
  - COMMAND=integration MR_VERSION=#master MOP_VERSION="#master" DEBUG=true
#  - COMMAND=integration MONTAGE_VERSION=15 MOP_VERSION=0.13 DEBUG=true
  - COMMAND=integration MONTAGE_VERSION=16.0.3 MOP_VERSION=latest DEBUG=true
  - COMMAND=integration MONTAGE_VERSION=latest MOP_VERSION=latest DEBUG=true
  - COMMAND=integration MONTAGE_VERSION=#master MOP_VERSION="#master" DEBUG=true
notifications:
  irc:
    channels:
      - "chat.freenode.net#montage"
    on_success: false
    template:
      - "%{author} broke the %{repository} tests on %{branch}: %{build_url}"